var issue = { action: 'created',
  issue:
   { url: 'https://api.github.com/repos/ethangodt/songlink/issues/1',
     repository_url: 'https://api.github.com/repos/ethangodt/songlink',
     labels_url: 'https://api.github.com/repos/ethangodt/songlink/issues/1/labels{/name}',
     comments_url: 'https://api.github.com/repos/ethangodt/songlink/issues/1/comments',
     events_url: 'https://api.github.com/repos/ethangodt/songlink/issues/1/events',
     html_url: 'https://github.com/ethangodt/songlink/pull/1',
     id: 158541016,
     number: 1,
     title: 'asdfawf',
     user:
      { login: 'ethangodt',
        id: 11809142,
        avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ethangodt',
        html_url: 'https://github.com/ethangodt',
        followers_url: 'https://api.github.com/users/ethangodt/followers',
        following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
        gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
        organizations_url: 'https://api.github.com/users/ethangodt/orgs',
        repos_url: 'https://api.github.com/users/ethangodt/repos',
        events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ethangodt/received_events',
        type: 'User',
        site_admin: false },
     labels: [],
     state: 'open',
     locked: false,
     assignee: null,
     milestone: null,
     comments: 1,
     created_at: '2016-06-05T06:53:51Z',
     updated_at: '2016-06-05T15:10:48Z',
     closed_at: null,
     pull_request:
	      { url: 'https://api.github.com/repos/ethangodt/songlink/pulls/1',
        html_url: 'https://github.com/ethangodt/songlink/pull/1',
        diff_url: 'https://github.com/ethangodt/songlink/pull/1.diff',
        patch_url: 'https://github.com/ethangodt/songlink/pull/1.patch' },
     body: 'fasdfsadf' },
  comment:
	   { url: 'https://api.github.com/repos/ethangodt/songlink/issues/comments/223818434',
     html_url: 'https://github.com/ethangodt/songlink/pull/1#issuecomment-223818434',
     issue_url: 'https://api.github.com/repos/ethangodt/songlink/issues/1',
     id: 223818434,
     user:
	      { login: 'ethangodt',
        id: 11809142,
        avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ethangodt',
        html_url: 'https://github.com/ethangodt',
        followers_url: 'https://api.github.com/users/ethangodt/followers',
        following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
        gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
        organizations_url: 'https://api.github.com/users/ethangodt/orgs',
        repos_url: 'https://api.github.com/users/ethangodt/repos',
        events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ethangodt/received_events',
        type: 'User',
        site_admin: false },
	     created_at: '2016-06-05T15:10:48Z',
	     updated_at: '2016-06-05T15:10:48Z',
	     body: 'here is a comment' },
  repository:
	   { id: 59544212,
     name: 'songlink',
     full_name: 'ethangodt/songlink',
     owner:
	      { login: 'ethangodt',
        id: 11809142,
        avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ethangodt',
        html_url: 'https://github.com/ethangodt',
        followers_url: 'https://api.github.com/users/ethangodt/followers',
        following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
        gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
        organizations_url: 'https://api.github.com/users/ethangodt/orgs',
        repos_url: 'https://api.github.com/users/ethangodt/repos',
        events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ethangodt/received_events',
        type: 'User',
        site_admin: false },
	     private: false,
	     html_url: 'https://github.com/ethangodt/songlink',
	     description: 'share music to anyone on any platform',
	     fork: true,
	     url: 'https://api.github.com/repos/ethangodt/songlink',
	     forks_url: 'https://api.github.com/repos/ethangodt/songlink/forks',
	     keys_url: 'https://api.github.com/repos/ethangodt/songlink/keys{/key_id}',
	     collaborators_url: 'https://api.github.com/repos/ethangodt/songlink/collaborators{/collaborator}',
	     teams_url: 'https://api.github.com/repos/ethangodt/songlink/teams',
	     hooks_url: 'https://api.github.com/repos/ethangodt/songlink/hooks',
	     issue_events_url: 'https://api.github.com/repos/ethangodt/songlink/issues/events{/number}',
	     events_url: 'https://api.github.com/repos/ethangodt/songlink/events',
	     assignees_url: 'https://api.github.com/repos/ethangodt/songlink/assignees{/user}',
	     branches_url: 'https://api.github.com/repos/ethangodt/songlink/branches{/branch}',
	     tags_url: 'https://api.github.com/repos/ethangodt/songlink/tags',
	     blobs_url: 'https://api.github.com/repos/ethangodt/songlink/git/blobs{/sha}',
	     git_tags_url: 'https://api.github.com/repos/ethangodt/songlink/git/tags{/sha}',
	     git_refs_url: 'https://api.github.com/repos/ethangodt/songlink/git/refs{/sha}',
	     trees_url: 'https://api.github.com/repos/ethangodt/songlink/git/trees{/sha}',
	     statuses_url: 'https://api.github.com/repos/ethangodt/songlink/statuses/{sha}',
	     languages_url: 'https://api.github.com/repos/ethangodt/songlink/languages',
	     stargazers_url: 'https://api.github.com/repos/ethangodt/songlink/stargazers',
	     contributors_url: 'https://api.github.com/repos/ethangodt/songlink/contributors',
	     subscribers_url: 'https://api.github.com/repos/ethangodt/songlink/subscribers',
	     subscription_url: 'https://api.github.com/repos/ethangodt/songlink/subscription',
	     commits_url: 'https://api.github.com/repos/ethangodt/songlink/commits{/sha}',
	     git_commits_url: 'https://api.github.com/repos/ethangodt/songlink/git/commits{/sha}',
	     comments_url: 'https://api.github.com/repos/ethangodt/songlink/comments{/number}',
	     issue_comment_url: 'https://api.github.com/repos/ethangodt/songlink/issues/comments{/number}',
	     contents_url: 'https://api.github.com/repos/ethangodt/songlink/contents/{+path}',
	     compare_url: 'https://api.github.com/repos/ethangodt/songlink/compare/{base}...{head}',
	     merges_url: 'https://api.github.com/repos/ethangodt/songlink/merges',
	     archive_url: 'https://api.github.com/repos/ethangodt/songlink/{archive_format}{/ref}',
	     downloads_url: 'https://api.github.com/repos/ethangodt/songlink/downloads',
	     issues_url: 'https://api.github.com/repos/ethangodt/songlink/issues{/number}',
	     pulls_url: 'https://api.github.com/repos/ethangodt/songlink/pulls{/number}',
	     milestones_url: 'https://api.github.com/repos/ethangodt/songlink/milestones{/number}',
	     notifications_url: 'https://api.github.com/repos/ethangodt/songlink/notifications{?since,all,participating}',
	     labels_url: 'https://api.github.com/repos/ethangodt/songlink/labels{/name}',
	     releases_url: 'https://api.github.com/repos/ethangodt/songlink/releases{/id}',
	     deployments_url: 'https://api.github.com/repos/ethangodt/songlink/deployments',
	     created_at: '2016-05-24T05:49:15Z',
	     updated_at: '2016-05-24T05:49:16Z',
	     pushed_at: '2016-06-05T06:53:51Z',
	     git_url: 'git://github.com/ethangodt/songlink.git',
	     ssh_url: 'git@github.com:ethangodt/songlink.git',
	     clone_url: 'https://github.com/ethangodt/songlink.git',
	     svn_url: 'https://github.com/ethangodt/songlink',
	     homepage: 'http://songl.ink',
	     size: 1213,
	     stargazers_count: 0,
	     watchers_count: 0,
	     language: 'JavaScript',
	     has_issues: false,
	     has_downloads: true,
	     has_wiki: true,
	     has_pages: false,
	     forks_count: 0,
	     mirror_url: null,
	     open_issues_count: 1,
	     forks: 0,
	     open_issues: 1,
	     watchers: 0,
	     default_branch: 'dev' },
  sender:
	   { login: 'ethangodt',
     id: 11809142,
     avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
     gravatar_id: '',
     url: 'https://api.github.com/users/ethangodt',
     html_url: 'https://github.com/ethangodt',
     followers_url: 'https://api.github.com/users/ethangodt/followers',
     following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
     gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
     organizations_url: 'https://api.github.com/users/ethangodt/orgs',
     repos_url: 'https://api.github.com/users/ethangodt/repos',
     events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
     received_events_url: 'https://api.github.com/users/ethangodt/received_events',
     type: 'User',
     site_admin: false } };

const pull_request = { action: 'created',
  comment:
   { url: 'https://api.github.com/repos/ethangodt/songlink/pulls/comments/65838867',
     id: 65838867,
     diff_hunk: '@@ -1,7 +1,6 @@\n {\n-  "parser": "babel-eslint",\n-  "env": {\n-    "browser": true,\n-    "node": true\n-  }\n+\t"env": {',
     path: '.eslintrc',
     position: 7,
     original_position: 7,
     commit_id: '12b68a1355663577ab344088139c9ad45c3e1ff3',
     original_commit_id: '12b68a1355663577ab344088139c9ad45c3e1ff3',
     user:
      { login: 'ethangodt',
        id: 11809142,
        avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ethangodt',
        html_url: 'https://github.com/ethangodt',
        followers_url: 'https://api.github.com/users/ethangodt/followers',
        following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
        gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
        organizations_url: 'https://api.github.com/users/ethangodt/orgs',
        repos_url: 'https://api.github.com/users/ethangodt/repos',
        events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ethangodt/received_events',
        type: 'User',
        site_admin: false },
     body: 'Really great.',
     created_at: '2016-06-06T05:37:50Z',
     updated_at: '2016-06-06T05:37:50Z',
     html_url: 'https://github.com/ethangodt/songlink/pull/2#discussion_r65838867',
     pull_request_url: 'https://api.github.com/repos/ethangodt/songlink/pulls/2',
     _links: { self: [Object], html: [Object], pull_request: [Object] } },
  pull_request:
	   { url: 'https://api.github.com/repos/ethangodt/songlink/pulls/2',
     id: 72654946,
     html_url: 'https://github.com/ethangodt/songlink/pull/2',
     diff_url: 'https://github.com/ethangodt/songlink/pull/2.diff',
     patch_url: 'https://github.com/ethangodt/songlink/pull/2.patch',
     issue_url: 'https://api.github.com/repos/ethangodt/songlink/issues/2',
     number: 2,
     state: 'open',
     locked: false,
     title: 'feat(stuff): this fixes the stuff that was a problem',
     user:
	      { login: 'ethangodt',
        id: 11809142,
        avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ethangodt',
        html_url: 'https://github.com/ethangodt',
        followers_url: 'https://api.github.com/users/ethangodt/followers',
        following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
        gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
        organizations_url: 'https://api.github.com/users/ethangodt/orgs',
        repos_url: 'https://api.github.com/users/ethangodt/repos',
        events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ethangodt/received_events',
        type: 'User',
        site_admin: false },
	     body: 'Hello! This is crazy.',
	     created_at: '2016-06-06T04:25:46Z',
	     updated_at: '2016-06-06T05:37:50Z',
	     closed_at: null,
	     merged_at: null,
	     merge_commit_sha: '5e553f489936379cb71cfb0435466f894680d641',
	     assignee: null,
	     milestone: null,
	     commits_url: 'https://api.github.com/repos/ethangodt/songlink/pulls/2/commits',
	     review_comments_url: 'https://api.github.com/repos/ethangodt/songlink/pulls/2/comments',
	     review_comment_url: 'https://api.github.com/repos/ethangodt/songlink/pulls/comments{/number}',
	     comments_url: 'https://api.github.com/repos/ethangodt/songlink/issues/2/comments',
	     statuses_url: 'https://api.github.com/repos/ethangodt/songlink/statuses/12b68a1355663577ab344088139c9ad45c3e1ff3',
	     head:
		      { label: 'ethangodt:dev',
	        ref: 'dev',
	        sha: '12b68a1355663577ab344088139c9ad45c3e1ff3',
	        user: [Object],
	        repo: [Object] },
	     base:
		      { label: 'ethangodt:redesign',
	        ref: 'redesign',
	        sha: 'f432e9bc061eb68a9a02bf1ff9237f84afecc70e',
	        user: [Object],
	        repo: [Object] },
	     _links:
		      { self: [Object],
	        html: [Object],
	        issue: [Object],
	        comments: [Object],
	        review_comments: [Object],
	        review_comment: [Object],
	        commits: [Object],
	        statuses: [Object] } },
  repository:
	   { id: 59544212,
     name: 'songlink',
     full_name: 'ethangodt/songlink',
     owner:
	      { login: 'ethangodt',
        id: 11809142,
        avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ethangodt',
        html_url: 'https://github.com/ethangodt',
        followers_url: 'https://api.github.com/users/ethangodt/followers',
        following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
        gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
        organizations_url: 'https://api.github.com/users/ethangodt/orgs',
        repos_url: 'https://api.github.com/users/ethangodt/repos',
        events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ethangodt/received_events',
        type: 'User',
        site_admin: false },
	     private: false,
	     html_url: 'https://github.com/ethangodt/songlink',
	     description: 'share music to anyone on any platform',
	     fork: true,
	     url: 'https://api.github.com/repos/ethangodt/songlink',
	     forks_url: 'https://api.github.com/repos/ethangodt/songlink/forks',
	     keys_url: 'https://api.github.com/repos/ethangodt/songlink/keys{/key_id}',
	     collaborators_url: 'https://api.github.com/repos/ethangodt/songlink/collaborators{/collaborator}',
	     teams_url: 'https://api.github.com/repos/ethangodt/songlink/teams',
	     hooks_url: 'https://api.github.com/repos/ethangodt/songlink/hooks',
	     issue_events_url: 'https://api.github.com/repos/ethangodt/songlink/issues/events{/number}',
	     events_url: 'https://api.github.com/repos/ethangodt/songlink/events',
	     assignees_url: 'https://api.github.com/repos/ethangodt/songlink/assignees{/user}',
	     branches_url: 'https://api.github.com/repos/ethangodt/songlink/branches{/branch}',
	     tags_url: 'https://api.github.com/repos/ethangodt/songlink/tags',
	     blobs_url: 'https://api.github.com/repos/ethangodt/songlink/git/blobs{/sha}',
	     git_tags_url: 'https://api.github.com/repos/ethangodt/songlink/git/tags{/sha}',
	     git_refs_url: 'https://api.github.com/repos/ethangodt/songlink/git/refs{/sha}',
	     trees_url: 'https://api.github.com/repos/ethangodt/songlink/git/trees{/sha}',
	     statuses_url: 'https://api.github.com/repos/ethangodt/songlink/statuses/{sha}',
	     languages_url: 'https://api.github.com/repos/ethangodt/songlink/languages',
	     stargazers_url: 'https://api.github.com/repos/ethangodt/songlink/stargazers',
	     contributors_url: 'https://api.github.com/repos/ethangodt/songlink/contributors',
	     subscribers_url: 'https://api.github.com/repos/ethangodt/songlink/subscribers',
	     subscription_url: 'https://api.github.com/repos/ethangodt/songlink/subscription',
	     commits_url: 'https://api.github.com/repos/ethangodt/songlink/commits{/sha}',
	     git_commits_url: 'https://api.github.com/repos/ethangodt/songlink/git/commits{/sha}',
	     comments_url: 'https://api.github.com/repos/ethangodt/songlink/comments{/number}',
	     issue_comment_url: 'https://api.github.com/repos/ethangodt/songlink/issues/comments{/number}',
	     contents_url: 'https://api.github.com/repos/ethangodt/songlink/contents/{+path}',
	     compare_url: 'https://api.github.com/repos/ethangodt/songlink/compare/{base}...{head}',
	     merges_url: 'https://api.github.com/repos/ethangodt/songlink/merges',
	     archive_url: 'https://api.github.com/repos/ethangodt/songlink/{archive_format}{/ref}',
	     downloads_url: 'https://api.github.com/repos/ethangodt/songlink/downloads',
	     issues_url: 'https://api.github.com/repos/ethangodt/songlink/issues{/number}',
	     pulls_url: 'https://api.github.com/repos/ethangodt/songlink/pulls{/number}',
	     milestones_url: 'https://api.github.com/repos/ethangodt/songlink/milestones{/number}',
	     notifications_url: 'https://api.github.com/repos/ethangodt/songlink/notifications{?since,all,participating}',
	     labels_url: 'https://api.github.com/repos/ethangodt/songlink/labels{/name}',
	     releases_url: 'https://api.github.com/repos/ethangodt/songlink/releases{/id}',
	     deployments_url: 'https://api.github.com/repos/ethangodt/songlink/deployments',
	     created_at: '2016-05-24T05:49:15Z',
	     updated_at: '2016-05-24T05:49:16Z',
	     pushed_at: '2016-06-06T04:25:46Z',
	     git_url: 'git://github.com/ethangodt/songlink.git',
	     ssh_url: 'git@github.com:ethangodt/songlink.git',
	     clone_url: 'https://github.com/ethangodt/songlink.git',
	     svn_url: 'https://github.com/ethangodt/songlink',
	     homepage: 'http://songl.ink',
	     size: 1213,
	     stargazers_count: 0,
	     watchers_count: 0,
	     language: 'JavaScript',
	     has_issues: false,
	     has_downloads: true,
	     has_wiki: true,
	     has_pages: false,
	     forks_count: 0,
	     mirror_url: null,
	     open_issues_count: 2,
	     forks: 0,
	     open_issues: 2,
	     watchers: 0,
	     default_branch: 'dev' },
  sender:
	   { login: 'ethangodt',
     id: 11809142,
     avatar_url: 'https://avatars.githubusercontent.com/u/11809142?v=3',
     gravatar_id: '',
     url: 'https://api.github.com/users/ethangodt',
     html_url: 'https://github.com/ethangodt',
     followers_url: 'https://api.github.com/users/ethangodt/followers',
     following_url: 'https://api.github.com/users/ethangodt/following{/other_user}',
     gists_url: 'https://api.github.com/users/ethangodt/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/ethangodt/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/ethangodt/subscriptions',
     organizations_url: 'https://api.github.com/users/ethangodt/orgs',
     repos_url: 'https://api.github.com/users/ethangodt/repos',
     events_url: 'https://api.github.com/users/ethangodt/events{/privacy}',
     received_events_url: 'https://api.github.com/users/ethangodt/received_events',
     type: 'User',
     site_admin: false } }


